local c = require('nvimpire.colors').colors

local M = {}

function M.get()
  return {
    ["@none"] = { fg = c.none, bg = c.none },
    ["@comment"] = { fg = c.comment, bg = c.none, italic = true },
    ["@preproc"] = { fg = c.pink, bg = c.none },
    ["@define"] = { fg = c.pink, bg = c.none },
    ["@operator"] = { fg = c.pink, bg = c.none },
    ["@punctuation.delimeter"] = { fg = c.fg, bg = c.none },
    ["@punctuation.bracket"] = { fg = c.fg, bg = c.none },
    ["@punctuation.special"] = { fg = c.pink, bg = c.none },
    ["@string"] = { fg = c.yellow, bg = c.none },
    ["@string.regex"] = { fg = c.red, bg = c.none },
    ["@string.escape"] = { fg = c.cyan, bg = c.none },
    ["@boolean"] = { fg = c.purple, bg = c.none },
    ["@character"] = { fg = c.pink, bg = c.none },
    ["@character.special"] = { fg = c.cyan, bg = c.none },
    ["@number"] = { fg = c.purple, bg = c.none },
    ["@float"] = { fg = c.purple, bg = c.none },
    ["@function"] = { fg = c.green, bg = c.none },
    ["@function.builtin"] = { fg = c.cyan, bg = c.none },
    ["@function.call"] = { fg = c.green, bg = c.none },
    ["@function.macro"] = { fg = c.pink, bg = c.none },
    ["@method"] = { fg = c.green, bg = c.none },
    ["@method.call"] = { fg = c.green, bg = c.none },
    ["@constructor"] = { fg = c.cyan, bg = c.none },
    ["@parameter"] = { fg = c.orange, bg = c.none, italic = true },
    ["@keyword"] = { fg = c.pink, bg = c.none },
    ["@keyword.function"] = { fg = c.pink, bg = c.none },
    ["@keyword.operator"] = { fg = c.pink, bg = c.none, bold = true },
    ["@keyword.return"] = { fg = c.pink, bg = c.none },
    ["@keyword.export"] = { fg = c.pink, bg = c.none },
    ["@conditional"] = { fg = c.pink, bg = c.none },
    ["@repeat"] = { fg = c.pink, bg = c.none },
    ["@debug"] = { fg = c.cyan, bg = c.none },
    ["@label"] = { fg = c.pink, bg = c.none },
    ["@include"] = { fg = c.pink, bg = c.none },
    ["@exception"] = { fg = c.pink, bg = c.none },
    ["@type"] = { fg = c.cyan, bg = c.none, italic = true },
    ["@type.builtin"] = { fg = c.cyan, bg = c.none, italic = true },
    ["@type.definition"] = { fg = c.cyan, bg = c.none, italic = true },
    ["@type.qualifier"] = { fg = c.pink, bg = c.none, italic = true },
    ["@storageclass"] = { fg = c.pink, bg = c.none },
    ["@attribute"] = { fg = c.pink, bg = c.none },
    ["@field"] = { fg = c.fg, bg = c.none },
    ["@property"] = { fg = c.fg, bg = c.none },
    ["@variable"] = { fg = c.fg, bg = c.none },
    ["@variable.builtin"] = { fg = c.purple, bg = c.none },
    ["@constant"] = { fg = c.purple, bg = c.none },
    ["@constant.builtin"] = { fg = c.purple, bg = c.none },
    ["@constant.macro"] = { fg = c.pink, bg = c.none },
    ["@namespace"] = { fg = c.pink, bg = c.none },
    ["@symbol"] = { fg = c.fg, bg = c.none },
    ["@text"] = { fg = c.none, bg = c.none },
    ["@text.strong"] = { fg = c.none, bg = c.none, bold = true },
    ["@text.emphasis"] = { fg = c.none, bg = c.none, italic = true },
    ["@text.underline"] = { fg = c.none, bg = c.none, underline = true },
    ["@text.strike"] = { fg = c.none, bg = c.none, strikethrough = true },
    ["@text.title"] = { fg = c.cyan, bg = c.none, bold = true },
    ["@text.literal"] = { fg = c.yellow, bg = c.none },
    ["@text.uri"] = { fg = c.none, bg = c.none, underline = true },
    ["@text.math"] = { fg = c.cyan, bg = c.none },
    ["@text.environment"] = { fg = c.pink, bg = c.none },
    ["@text.environment.name"] = { fg = c.cyan, bg = c.none, italic = true },
    ["@text.reference"] = { fg = c.purple, bg = c.none },
    ["@text.todo"] = { fg = c.cyan, bg = c.none, bold = true },
    ["@text.note"] = { fg = c.cyan, bg = c.none, italic = true },
    ["@text.warning"] = { fg = c.cyan, bg = c.none, bold = true },
    ["@text.danger"] = { fg = c.orange, bg = c.none, bold = true },
    ["@tag"] = { fg = c.pink, bg = c.none },
    ["@tag.attribute"] = { fg = c.green, bg = c.none },
    ["@tag.delimiter"] = { fg = c.fg, bg = c.none },

    ["@definition.parameter"] = { fg = c.orange, bg = c.none },

    ["@constructur.typescript"] = {
      fg = c.purple,
      bg = c.none,
    },

    -- TSX
    ["@tag.attribute.tsx"] = { fg = c.green, italic = true },
    ["@tag.delimiter.tsx"] = { fg = c.fg, bg = c.none },

    -- JSON
    ["@label.json"] = { fg = c.cyan, bg = c.none },
  }
end

return M
